### ISSUE TITLE
Support for composer.json - especially in combination with autoload and Class Alias maps?

### ISSUE THREAD

**Issue by AndreasA** [TYPO3/CmsComposerPackageGenerator#12]
Now that 7.6 is out it would really be great if http://composer.typo3.org were to support the autoload (e.g. currently it always uses all classes but the autoloader might only require some which should be in a composer.json if it exists) and class alias map defintion from composer.json

**Comment by AndreasA** [comment]
I just checked the packages.json and that already seems to be the case for newer extensions that contain a json so I guess it can be closed

**Comment by AndreasA** [comment]
Althought not all extensions with composer.json seem to have the corresponding information in packages.json
For instance for static_info_tables although it has a composer.json the name seems to be ignored.

**Comment by helhum** [comment]
closed in favor of #21
