### ISSUE TITLE
Use provider-urls

### ISSUE THREAD

**Issue by copitz** [TYPO3/CmsComposerPackageGenerator#14]
Currently using composer.typo3.org as composer repository makes composer update a pain as it has to load the complete repository. There is a solution for this problem which is used by large repositories as packagist.org:

https://getcomposer.org/doc/05-repositories.md#provider-includes-and-providers-url

Unfortunately it seems like satis doesn't support those, thus we'd have to find a way around it or possibly fork it. I'd like to help with this, if you agree on that problem :)

Cheers,
Christian

**Comment by pniederlag** [comment]
It sounds like a simple problem to me to split a large file into small chunks. ;) If you(or someone else) finds the time to improve satis, be sure to get a load of praise from my side. 
Are we sure this would speedup composer update? Do you have an estimate on the time it would require? Maybe carry this issue to upstream satis to target the proper audience?
Thx for pointing this out.

**Comment by alexanderschnitzler** [comment]
I am very much aware of that issue and already wondered how packagist itself manages to split all packages into smaller files. I guess Satis simply does not provide a good solution so far and I would like to not have it forked. At least this issue will be on the table during the next composer based code sprint end of january.

**Comment by copitz** [comment]
Hi Peter, hi Alexander,

it's true: Satis should handle this and it's true as well that it simply doesn't support that. Implementing the feature there (or in a fork for now) would be a good idea - maybe we should ask @Seldaek about his 2 cents upfront.

However packagist manages the provider dumping itself - likely (here)[https://github.com/composer/packagist/blob/master/src/Packagist/WebBundle/Package/SymlinkDumper.php]. Maybe using a packagist fork for composer.typo3.org would be an idea as well but that would actually mean building a second TER, right?

**Comment by Seldaek** [comment]
I thought satis supported that, but I am not sure to be honest I don't have time to maintain it anymore. I rather spend my time on composer, packagist and [toran proxy](https://toranproxy.com) which is a superior solution IMO for most satis use cases. Your use case of building a large public repo is more in line with what packagist does though. There isn't a great answer in that domain because most organizations have their own sort of requirements and as such it's probably good to roll your own I would say. The file format is pretty simple to build really.. The packagist code isn't usable in isolation as it depends on the packagist data store and doctrine entities.

Just my raw thoughts.. I hope it helps, but I can't do much more sorry :)

**Comment by alexanderschnitzler** [comment]
Thanks for the insight.
I also considered using and running packagist instead but at the moment it conflicts functionality wise with our old download-based solution. Actually it's more a political issue than a technical. I guess even forking Satis or whatever would be done quickly but as we are planning to talk about all this in January I don't see why we should tackle this now, especially during the christmas time. :)

**Comment by pgampe** [comment]
TER is supposed to be moved to an own service anyway. Not timeline yet, but will happen with the split of t3o into community, commercial and marketplace (TER, Shop, etc).
We will only have 6.2 and 7.6 LTS to support for legacy API, thus we can just create anything we want there or even to for an dedicated service and only list extensions information and download links on the website.

**Comment by copitz** [comment]
I meanwhile forked satis (https://github.com/composer/satis/pull/295)

If you want to use this fork (what would be absolutely great until you found a more sophisticated solution), I'd make a PR for that.

**Comment by copitz** [comment]
In the meanwhile the PR is merged into satis master. Please only add `"providers": true` to the satis configuration.

**Comment by andygrunwald** [comment]
This might be affect TYPO3 as well: https://github.com/composer/satis/issues/367

**Comment by copitz** [comment]
Which is solved now as well

**Comment by andygrunwald** [comment]
<3
