### ISSUE TITLE
packages-TYPO3Extensions-archive.json points to http url where it should point to https

### ISSUE THREAD

**Issue by pniederlag** [TYPO3/CmsComposerPackageGenerator#16]
TER-Extensions currently point to:

    # scheme
    dist":{"url":"http//typo3.org/extensions/repository/...."}

Unfortunatly the extensions are served from https:// instead nowadays. This breaks weird setups where composer install does not follow header location redirects.

**Comment by alexanderschnitzler** [comment]
So, can this be closed? If so, please go ahead. :)
