### ISSUE TITLE
Class-Aliases do not work

### ISSUE THREAD

**Issue by rvock** [TYPO3/CmsComposerPackageGenerator#21]
When creating the package-array, the `extra`-property is not set and no `class-alias-maps` are added. This leads to strange bugs, when installing an extension using e.g. `typo3-ter/crawler` (which misses the `extra`-property) instead of the "real" composer name `aoepeople/crawler` which does contain the `extra`-property.

[CreateTerExtensionJsonCommand:: getPackageArray](https://github.com/TYPO3/CmsComposerPackageGenerator/blob/0ab57d/src/Classes/Command/CreateTerExtensionJsonCommand.php#L144) should check if there is a composer.json within the project or a Migrations-folder and generate the `extra`-property.

**Comment by helhum** [comment]
This requires corresponding changes in https://git-t3o.typo3.org/t3o/ter so that the extra section in composer.json is exposed, which can the be picked up here

**Comment by gilbertsoft** [comment]
Because the TYPO3 Composer Repository is deprecated anyway I'm not going to spend time on this issue and will close it now. See also https://composer.typo3.org.
