### ISSUE TITLE
Prefer/Recommend packages from packagist

### ISSUE THREAD

**Issue by pixelbrackets** [TYPO3/CmsComposerPackageGenerator#22]
Helmut Hummel helped me at T3DD17 with Composer and during this workshop we discovered, that composer.typo3.org enforces "typo3-ter" as vendor name for all packages and that this may cause trouble with packages. Especially the ones which are not pushed to TER anymore.

We I tried to load the introduction package with ```typo3-ter/introduction``` I got an error during the CMS installation. Instead I should have used the key ```typo3/cms-introduction```. I cant see this at any point however.

Introduction package on composer.typo3.org: https://composer.typo3.org/satis.html#typo3-ter/introduction
Introduction package on Packagist: https://packagist.org/packages/typo3/cms-introduction

Satis should recommend/prefer the package from packagist. 

This is the currently the case with EXT:typo3-console. The message was added manually though, we need an automatic approach.

TYPO3 Console on composer.typo3.org: https://composer.typo3.org/satis.html#!/typo3-console
TYPO3 Console on Packagist: https://packagist.org/packages/helhum/typo3-console

![bildschirmfoto vom 2017-08-07 16-22-36](https://user-images.githubusercontent.com/1592995/29031194-b0825e9a-7b8d-11e7-8708-9e393a53dcc2.png)

Workflow: 
1. Fetch extension
1. composer.json exists?
    1. Yes -> name key exists on Packagist?
        1. Yes -> Add public note to recommend package from packagist
        1. No -> Overwrite vendor name of package with ```typo3-ter```, to serve the package from TER instead
    1. No -> generate composer.json with ```typo3-ter``` as vendor name

**Comment by pixelbrackets** [comment]
Note: Some extensions have two entries on composer.typo3.org. For example EXT:crawler (```typo3-ter/crawler``` and ```aoepople/crawler```): https://composer.typo3.org/satis.html#!/crawler

**Comment by alexanderschnitzler** [comment]
> Odd: Some have an entry on composer.typo3.org, but when I download them they dont contain a composer.json.

It's not odd. Extensions in the TER don't need a composer.json at all. There is a virtual one generated anyway for each extension, so it can be downloaded with composer via composer.typo3.org.

**Comment by alexanderschnitzler** [comment]
btw: we had an algorithm in place that let people set their repository urls, so we could fetch the packages from there instead of from TER. However, that concept was flawed and had some issues regarding security.

Nevertheless, I'd say that it's the responsibility of the developers to see where they get their packages from instead of implementing a fallback. I'd rather get rid of composer.typo3.org sooner than later. Implementing a fallback could make people lazy while not understanding where their packages actually come from.

**Comment by pixelbrackets** [comment]
> It's not odd. Extensions in the TER don't need a composer.json at all. There is a virtual one generated anyway for each extension, so it can be downloaded with composer via composer.typo3.org.

Yes, I know that a composer.json is autogenerated for extensions missing it. But I thought that this generated file is stored somewhere. When I download the package with composer I get the extension with a (autogenerated) composer.json. But when I download the same package manually (Search for »dd-googlesitemap-dmf«, click version 2.0.0 in the release column), it is not there. It expected them to deliver the same content.

![bildschirmfoto vom 2017-08-09 17-01-16](https://user-images.githubusercontent.com/1592995/29128986-baf1b27e-7d25-11e7-93df-3cb104054e21.png)

> I'd rather get rid of composer.typo3.org sooner than later. Implementing a fallback could make people lazy while not understanding where their packages actually come from.

Then thats a missunderstanding. It is not intended to build a fallback. Instead a warning should appear which tells the user "Hey, you use a package from typo3-ter, but you should use X instead". So it should nudge developers to make use of Packagist.

**Comment by alexanderschnitzler** [comment]
> Then thats a missunderstanding. It is not intended to build a fallback. Instead a warning should appear which tells the user "Hey, you use a package from typo3-ter, but you should use X instead". So it should nudge developers to make use of Packagist.

👍

**Comment by helhum** [comment]
fixed with b54ac2055ab4d3710b25f1dcd9e59933a41fd302
