### ISSUE TITLE
Remove necessity to add typo3 user as maintainer on packagist

### ISSUE THREAD

**Issue by helhum** [TYPO3/CmsComposerPackageGenerator#4]
tl;dr I propose to just remove the section that proposes publishing TYPO3 CMS extensions on packagist.org from the composer.typo3.org website

I don't know it this is the right place to put this as request, but since this repo is kind of related to composer.typo3.org I thought it might make sense here.

My major complaint is about the following advice on composer.typo3.org:
`Add "typo3" as additional maintainer of your package on Packagist. This is required to have Gerrit's hook correctly triggering the update on Packagist.`

While I understand the usefulness of a sync feature for git.typo3.org repos with packagist.org, I propose to nevertheless disable this feature or implement it differently. Here is why:

* The typo3 user/maintainer on packagist is an official entity. It should only be associated with official packages (packages representing the TYPO3 product family or being part of it) This state should be reflected when visiting this URL: https://packagist.org/users/typo3/
* The requirement to allow a foreign account to maintain (meaning delete, change URL ...)  someones package (for implementing a sync feature) is a security design flaw. Offering such a flawed "concept" IMHO harms the reputation of TYPO3
* Promoting packagist.org as a repository for TYPO3 extensions/ packages (this for me includes third party Flow/ Neos packages) is wrong. I absolutely understand that we cannot provide an alternative right now, but we must rather sooner or later set up our own "packagist" which acts as repository for Flow/ Neos packages, (legacy) TER extensions and (new) TYPO3 CMS Extensions. We need this, because only then we (as a community) can offer "premium" services like cleaning out or hiding outdated or insecure packages.

I know that the things I've written here would require quite a bit of planning and work. I'm happy to help here, but cannot promise something short term.

Because of that I propose to just remove the section that proposes publishing TYPO3 CMS extensions on packagist.org from the composer.typo3.org website.

**Comment by kaystrobach** [comment]
:+1: for enhancing ter with packagist support

**Comment by lars85** [comment]
:+1:

**Comment by t3dev** [comment]
Your comment seems pretty reasonable to me. You have my full support on pushing forward composer and providing a decent TYPO3 related packagist resource. I addet this on my radar, thx for popping this up.

**Comment by astehlik** [comment]
I also agree that the Composer handling can be improved :)

One possible solution I see for the problem with the TYPO3 maintainer access is to integrate the Packagist webhooks (https://packagist.org/about):

> If you use BitBucket, GitLab or other non-supported method you can add a "POST" hook or Push Event and then enter 'https://packagist.org/api/update-package?username=XXX&apiToken=YYY' as the URL. To manually send update notices from other services you can build up a POST request to the previous URL and send the following JSON request body: {"repository": { "url": "...the VCS url Packagist should update..."}}. Do not forget to send a Content-Type header set to application/json too.

For this to work we need the possibility to configure your Packagist username and API Token in somwhere in your profile or in the Extension properties.

As far as I can see we need a better Git infrastructure for a good Composer integration. The question is: do we want do do it ourselves (Gitlab, Atlassian) or do we rely on other services like Github, where Composer is already integrated nicely.

I think we should concentrate our resources on making TYPO3 better and use as many available services as possible and integrate them for our needs.

To mark Extensions as insecure we could still setup a minimal infrastructure that stores information about security issues and is queried during install. Composer already has the possibility to use custom installers.

I'm currently not sure how we can integrate Gerrit with Github though. Gerrit would need push access to the (Extension) repositories or it needs to trigger some kind of hook that executes a pull from Gerrit in the Github repository.

**Comment by NamelessCoder** [comment]
Thanks @helhum for picking this up. I only have a few bullet-points worth of input:

1. EM should *depend* on composer and require every package to have a composer manifest.
2. EM should not care if a dependency is a TYPO3 extension or library (or something completely different like a storage of markdown files).
3. EM should detect which packages are TYPO3 extensions and treat those specially (install directory, loading ext_* files, etc).
4. EM should filter out insecure/incompatible packages.
5. Packagist should be used, not a self-hosted service.
6. Turn TER into a frontend for composer, not vice versa. TER can operate on metadata - TER should not be dictating extension uploads to packagist.

Essentially: we should fight the NIH and use as many existing services and methodologies as possible, and packagist is an obvious choice as master metadata repository.

**Comment by smichaelsen** [comment]
+1 for Claus 
If we'd allow to load arbitrary composer packages that would be an enormous improvement. We shouldn't try (anymore) to build or own package management but build on top of the very good industry standard.

**Comment by cedricziel** [comment]
Basically @NamelessCoder summed it up very well.

My POV is that we desperately need to have easier access to 3rd party packages. (Which would also allow integrating proven components even into the core much, much easier.)

**Comment by jaguerra** [comment]
+1 for Claus

IMHO we should embrace composer/packagist as much as we can. The TER has been a fantastic tool given that many years ago there where no standard, widely adopted packaging solution for the PHP ecosystem was available. But nowadays I see no strong reason not to rely on composer and allow much better interoperability.

**Comment by kaystrobach** [comment]
i would really like to see full composer support.
BUT on the otherhand i would like to have the central repo, which allows use to blacklist unsecure extensions etc. which would be quite easy by adding a simple alternativ packagist repo, which is hosted on TYPO3.org ... this also allows aus tight coupling with our other services

**Comment by jaguerra** [comment]
Blacklisting unsecure extensions seems to be the killer feature of TER that should have its counterpart on composer. But I'm sure there's a plausible (and decoupled) solution for that :)

**Comment by astehlik** [comment]
@jaguerra Steffen Müller posted interesting suggestion for this on Twitter:

> Steffen Müller ‏@stmllr 
> @helhum publish a security package which contains vulnerable packages as conflicts. Make CMS depend on this package https://t.co/Iz9OQdvIw1

https://twitter.com/stmllr/status/562735389455421440

**Comment by kaystrobach** [comment]
;) this package composer.json can get pretty large in a short amount of time :smile:

**Comment by cedricziel** [comment]
Doesnt matter, it's text which gets compressed ;)

Maybe someone should get in touch with the packagist folks? Maybe they provide some mechanism we dont know about? Or at least have a hint...

**Comment by NamelessCoder** [comment]
> ;) this package composer.json can get pretty large in a short amount of time

Let's count a bit. There are approximately six thousand TER extensions. Let's be crazy for a second and assume that each and every extension has at least 10 insecure versions out there. To match to insecure version numbers, approximately 80 bytes are required (10 groups of three-segment version numbers in quotes separated by spaces) and let's reserve another 20 bytes for the extension key.

This would, given 10 insecure versions of every single extension, result in around 6,000 * 100 bytes equalling 600KB.

I personally wouldn't use avoiding (in the ridiculous extreme) 600 KB of text as an argument for creating our own clone of packagist... but I digress ;)

**Comment by fudriot** [comment]
I have [just removed](https://review.typo3.org/#/c/36669) the paragraph on composer.typo3.org that talked about synch of git.typo3.org with Packagist (the purpose of this ticket). I am all for having a better support of  Composer in our CMS more particularly for linking external package. Thomas M. is working on that but I believe you know that already. Technically this ticket is "solved".
