### ISSUE TITLE
List insecure extensions

### ISSUE THREAD

**Issue by alexanderschnitzler** [TYPO3/CmsComposerPackageGenerator#8]
# Problem

Currently the package generator completely removes insecure versions of extensions from the generated `composer.json` which is a real flaw due to several reasons:
- A repository like packagist or `composer.typo3.org`is not responsible for deciding which kind of source code is to be fetched. It should only act as a repository, i.e. listing all versions of a decent package.
- Whenever a package is removed because it is blacklisted, there is a chance that deployments, that rely on insecure versions, completely fail. Even if a package version is insecure it must be possible to `download` it.
# Solution

Include insecure package versions and mark them as such, so either a composer installer can warn/ask a user during installation or the future package manager (the one that uses composer in the background) can warn/ask the user or prevent an installation.

First step is to make sure to include all package versions again and to flag them. This can be done inside this repository and I will create a pull request for it.

Imho the next step would be to adjust the typo3 composer autoloader to at least warn users during installation that they are installing an insecure version and that there is a secure version available.

**Comment by gilbertsoft** [comment]
Fixed by #9 so I'm going to close this issue.
